resources:
  - url: http://127.0.0.1:5000/floor3d-card.js
    type: module 
views:
  - cards:
      - type: custom:floor3d-card
        name: Floor3d Card Development
        entity: sun.sun
        test_gui: true
